main_resume/urls.py
from django.urls import path
from . import views

app_name = 'main_resume'

urlpatterns = [
    path('', views.home, name='home'),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("success/", views.success, name="success"),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_resume.urls')),
]

main_resume/models.py
from django.db import models

# Create your models here.

main_resume/forms.py
from django import forms
from django.core.mail import send_mail
import logging

logger = logging.getLogger(__name__)

class ContactForm(forms.Form):
    name = forms.CharField(label = 'Your First and Last name', max_length = 100)
    email_address = forms.EmailField(max_length = 150)
    message = forms.CharField(widget = forms.Textarea, max_length=2000)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
        self.cleaned_data["name"],
        self.cleaned_data["message"],
        self.cleaned_data["email_address"]
        )
        send_mail(
        "Site message",
        message,
        "patrickidungafa2@gmail.com",
        ["patrickidungafa2@gmail.com"],
        fail_silently=False,
        )

main_resume/views.py
from django.shortcuts import render
from . import forms
from django.views.generic.edit import FormView



def home(request):
    return render(request, 'main_resume/home.html')

def success(request):
    return render(request, 'main_resume/success.html')

class ContactView(FormView):
    template_name = "main_resume/contact.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

main_resume/templates/main_resume/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{% static '/css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="
    sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Personal Resume</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">
        <img src="{% static '/images/zuri-logo.jpeg' %}" width="50" height="50" alt="Resume-logo"/>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class='nav-item {% if request.path == "/" %}active{% endif %}'>
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item {% if request.path == '/about_us/' %}active{% endif %}">
            <a class="nav-link" href="/contact/">Contact Me</a>
          </li>
        </ul>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

main_resume/templates/main_resume/contact.html
{% extends "main_resume/base.html" %}

{% block content %}
  <hr>
    <h2>Contact us</h2>
    <p>Please fill the form below to contact us</p>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        {{ form.name.label_tag }}
        <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" 
        id="id_name" name="name" placeholder="Your full name" value="{{ form.name.value|default:'' }}">
        {% if form.name.errors %}
          <div class="invalid-feedback">
            {{ form.name.errors }}
          </div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.email_address.label_tag }}
        <input type="text" class="form-control {% if form.email_address.errors %}is-invalid{% endif %}" 
        id="id_email" name="email_address" placeholder="Your email" value="{{ form.email_address.value|default:'' }}">
        {% if form.email_address.errors %}
          <div class="invalid-feedback">
            {{ form.email_address.errors }}
          </div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.message.label_tag }}
        <textarea class="form-control {% if form.message.errors %}is-invalid{% endif %}"
        id="id_message" name="message" rows="3" placeholder="Write us a Message">
          {{ form.message.value|default:"" }}
        </textarea>
        {% if form.message.errors %}
          <div class="invalid-feedback">
            {{ form.message.errors }}
          </div>
        {% endif %}
      </div>

      <button type="submit" class="btn btn-primary">
        Submit
      </button>
    </form>
{% endblock content %}

main_resume/templates/main_resume/home.html
{% extends "main_resume/base.html" %}
{% load static %}
{% block content %}  
  <br>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="card card-body h-100 border-info" id="profile-wrapper">
          <img id="profile-pic" src="{% static 'images/patrick.jpg' %}" >
          <br>
          <h4>Hi, I'm Patrick!</h4>
          <p>A beginner in django/Python but absolutely loving it.</p>
        </div>
      </div>

      <div class="col-md-9">
        <div class="card card-body h-100 border-info">
          <h4>My Journey as a Developer</h4>
          <br>
          <p>I wrote my first ever "Hello World" program in Python on February 14 2020 (while
            it didn't seem like much) i quickly fell in love with Python and decided that i have 
            to get better at Python as i soon discovered that it has endless opportunities.</p>

          <p>After spending about four months trying to grasp the concepts in Python, i decided i
            needed to up my game otherwise get stuck, so i started learning django and used it to
            build some personal projects that i didn't finish because i got stuck on the way.</p>
            
          <p>I am still looking at django and i'm getting better by the day with python and Django.</p>
            
          <ul class="social-links">
            <li><img class="social" src="{% static 'images/facebook.png' %}"></li>
            <li><img class="social" src="{% static 'images/linkedIn.png' %}"></li>
            <li><img class="social" src="{% static 'images/twitter.png' %}"></li>
            <li><img class="social" src="{% static 'images/github.png' %}"></li>
          </ul>

        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-6">
        <div class="card card-body h-100">
          <h5>My Experience as a developer</h5>
          <br>
          <p>I haven't had much experience as i'm currently looking to get some through
          this internship.</p>
          <p>In my spare time, i have built an uncompleted e-commerce site for books, a blog
          that i am yet to complete, an e-learning journal and a discord bot.</p>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card card-body h-100">
          <h5>What I know</h5>
          <br>
          <p>Python, Django, HTML/CSS, Postgres</p>
          <p>PS: Working on Datascience and Machine Learning.</p>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-6">
        <div class="card card-body h-100">
          <h5>How I Learn</h5>
          <br>
          <p>Reverse Engineer and build ugly Prototypes First.</p>

          <p>I can learn just about anything by having a final product to tear apart piece by
            piece. I break the code where i need to figure out why things work the way they do.
            Documentation is just a reference.</p>
        </div>
      </div>
      
      <div class="col-md-6">
        <div class="card card-body h-100">
          <h5>My Short Term Goals</h5>
          <br>
          <p>Is to gather as much experience as possible which will enable me have an edge is this competive
            market</p> 
        </div>
      </div>
    </div>
    <br>
  </div>

{% endblock content %}

main_resume/templates/main_resume/success.html
<p>Your Enquiries has successfully been sent, we will reach back to you shortly.</p>
<p>Tap here<a href="main_resume/home"></a> to go back to homepage</p>